In [1]:
import numpy as np


In [5]:

w1,w2,w3=0.4,0.3,0.5
np.zeros((2,1))

array([[0.],
       [0.]])

In [2]:
kanto_temp = 73
kanto_rainfall = 67
kanto_humidity = 43

In [3]:
kanto_yield_apples = kanto_temp * w1 + kanto_rainfall * w2 + kanto_humidity * w3
kanto_yield_apples

70.8

In [5]:
print("The expected yield of apples in kanto region is {} tons per hectare  ".format(kanto_yield_apples))

The expected yield of apples in kanto region is 70.8 tons per hectare  


In [6]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

In [7]:
weights=[w1,w2,w3]

In [8]:
def crop_yield(region,weights):
    result=0
    for r ,x in zip(region,weights):
        result+=r*x
    return result


In [9]:
crop_yield(kanto,weights)

70.8

converting  alist into array

In [12]:
kanto=np.array(kanto)

In [ ]:
type(kanto)

In [13]:
np.size

<function numpy.size(a, axis=None)>

In [14]:
arr1=np.array([[2,4,3,4],[3,4,5,6]])

In [15]:
arr1.shape

(2, 4)

In [16]:
np.dot(kanto,weights)

70.8

In [ ]:
# can acheive the above by given method

In [17]:
(kanto*weights).sum()

70.8

In [18]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

In [19]:
arr1*arr2

array([ 4, 10, 18])

In [20]:
arr2.sum()

15

In [ ]:
#Benefits of using numpy arrays

Numpy arrays offer the following benefits over Python lists for operating on numerical data:

Ease of use: You can write small, concise, and intuitive mathematical expressions like (kanto * weights).sum() rather than using loops & custom functions like crop_yield.
Performance: Numpy operations and functions are implemented internally in C++, which makes them much faster than using Python statements & loops that are interpreted at runtime

arr1=list(range(10000000))

In [21]:
arr1=list(range(1000000))

In [22]:
arr2 = list(range(1000000, 2000000))

In [23]:
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [24]:
%%time 
result=0
for x1,x2 in zip(arr1,arr2):
    result+=x1*x2
result

Wall time: 204 ms


833332333333500000

In [25]:
%%time
np.dot(arr1_np ,arr2_np)

Wall time: 998 µs


-1942957984

In [26]:
import jovian

In [27]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "raishivam571/intro-numpy" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/raishivam571/intro-numpy


'https://jovian.ai/raishivam571/intro-numpy'

# Multi dimensional array

In [3]:
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])

In [4]:
climate_data.ndim

2

In [33]:
 climate_data.dtype

dtype('int32')

In [36]:
# matrix multiplication

In [37]:
np.matmul(climate_data,weights)

array([ 70.8,  94.8, 104. ,  72.2,  91.4])

# working with csv files

In [38]:
import urllib.request
urllib.request.urlretrieve( 'https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x2a37d542fa0>)

In [45]:
climate_data=np.genfromtxt('climate.txt',delimiter=',',skip_header=1)

In [47]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [48]:
climate_data.shape

(10000, 3)

In [49]:
yields=np.matmul(climate_data,weights)

In [50]:
yields

array([82.3, 70.1, 75.6, ..., 87.2, 94.8, 86.5])

In [51]:
yields.shape

(10000,)

In [66]:
climate_result=np.concatenate((climate_data,yields.reshape(10000,1)),axis=1)

In [56]:
climate_result

array([[25. , 76. , 99. , 82.3],
       [39. , 65. , 70. , 70.1],
       [59. , 45. , 77. , 75.6],
       ...,
       [99. , 62. , 58. , 87.2],
       [70. , 71. , 91. , 94.8],
       [92. , 39. , 76. , 86.5]])

In [59]:
a=np.array([[2,3,4],[6,7,8]])
b=np.array([[0,9,8],[6,5,4]])

In [62]:
a_result=np.concatenate((a,b,),axis=1)

In [63]:
a_result

array([[2, 3, 4, 0, 9, 8],
       [6, 7, 8, 6, 5, 4]])

In [72]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "raishivam571/intro-numpy" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/raishivam571/intro-numpy


'https://jovian.ai/raishivam571/intro-numpy'

# Arithmetic operations, broadcasting and comparison

In [75]:
arr2 = np.array([range(1,5), 
                range(5,9),
                 range(9,13)])

In [76]:
arr3 = np.array([[11, 12, 13, 14], 
                 [15, 16, 17, 18], 
                 [19, 11, 12, 13]])

In [77]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [78]:
arr2+3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [79]:
# we can do +,-,/,* to crosponding element 

In [81]:
#Array Broadcasting


In [82]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [83]:
arr4 = np.array([4, 5, 6, 7])

In [84]:
arr2+arr4

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

Array Comparison

In [88]:
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[2, 2, 3], [1, 2, 5]])


In [89]:
arr1==arr2

array([[False,  True,  True],
       [False, False,  True]])

In [90]:
arr1!=arr2

array([[ True, False, False],
       [ True,  True, False]])

Array comparison is frequently used to count the number of equal elements in two arrays using the sum method. Remember that True evaluates to 1 and False evaluates to 0 when booleans are used in arithmetic operations.

In [91]:
# if we have to find the the numbers of element which are same at crosponding postion

In [92]:
(arr1==arr2).sum()

3

In [94]:
#Array indexing and slicing

In [95]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

In [97]:
arr3[1,0,1]

16.0

In [103]:
arr3[1:,1:,1:]

array([[[92. , 36. , 18. ]],

       [[18. , 19.5, 43. ]]])

In [105]:
arr3[:2, 1:]

array([[[13., 14., 15., 19.]],

       [[63., 92., 36., 18.]]])

In [106]:
np.random.rand(5)

array([0.31443535, 0.61501943, 0.74216114, 0.22417991, 0.27143669])

In [108]:
np.random.randn(2, 3)# randn for normal distribution array mean will be zero

array([[ 0.34820977,  0.61498704, -1.05408423],
       [ 0.40155113, -2.07615877, -0.6740518 ]])

In [109]:
np.full([2, 3], 42)

array([[42, 42, 42],
       [42, 42, 42]])

In [6]:
arr=np.arange(100)
arr1 = arr.reshape(2, 5, 2, -1)

In [7]:
arr1.shape

(2, 5, 2, 5)